"""empty message

Revision ID: 9cbb40ddbc61
Revises: 31896ed52ff7
Create Date: 2025-04-06 21:29:59.387903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbb40ddbc61'
down_revision = '31896ed52ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))
        batch_op.drop_column('avat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avat', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
