"""add qr code fields

Revision ID: fb8893e1dfc8
Revises: 9cbb40ddbc61
Create Date: 2025-04-16 21:53:31.167162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8893e1dfc8'
down_revision = '9cbb40ddbc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('qr_code_token_expiration', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_qr_code_token'), ['qr_code_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_qr_code_token'))
        batch_op.drop_column('qr_code_token_expiration')
        batch_op.drop_column('qr_code_token')

    # ### end Alembic commands ###
